### ISSUE TITLE
Unable to connect to get response from NLB from outside the private subnet

### ISSUE THREAD

**Issue by ianleon** [aws-ia/cfn-ps-clickhouse-cluster#22]
I am unclear about how I (or one of my apps) is supposed to connect to the database.

**Comment by qiaow02** [comment]
Hi,
For security reasons, by default, ClickHouse can only be deployed in private subnets, and is not accessible to the public network.   
Your client needs to also be deployed in the same private subnets, or open the access restrictions of the private subnets security group according to your needs.   
According to the solution design, NLB provides the HTTP protocol for port 8123. If you want to use Clickhouse-client, you need to use port 9000 to directly connect to each server in ClickHouse cluster.

**Comment by ezotrickser** [comment]
did you find a solution?
